name: Python CI

on: [push, pull_request]  # Triggers on pushes/PRs

jobs:
  test:
    runs-on: ubuntu-latest  # Uses a clean Ubuntu VM
    
    steps:
    # 1. Check out your code
    - uses: actions/checkout@v4
    
    # 2. Set up Python (THIS IS WHERE YOUR COMMANDS GO)
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    # 3. Install pytest (YOUR FIRST COMMAND)
    - name: Install pytest
      run: pip install pytest
    
    # 4. Run tests (YOUR SECOND COMMAND)
    - name: Run tests
      run: pytest